# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ichinoseyuuki <ichinoseyuuki@student.42    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/06 13:35:07 by ichinoseyuu       #+#    #+#              #
#    Updated: 2023/02/20 11:10:05 by ichinoseyuu      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	libft.a
SRCS	=	ft_isalpha.c	\
			ft_isalnum.c	\
			ft_isascii.c	\
			ft_isdigit.c	\
			ft_isprint.c	\
			ft_strlen.c		\
			ft_memset.c		\
			ft_bzero.c		\
			ft_memcpy.c		\
			ft_memmove.c	\
			ft_strlcpy.c	\
			ft_strlcat.c	\
			ft_strnstr.c	\
			ft_atoi.c		\
			ft_tolower.c	\
			ft_toupper.c	\
			ft_strncmp.c	\
			ft_strchr.c		\
			ft_strrchr.c	\
			ft_memcmp.c		\
			ft_memchr.c		\
			ft_putchar_fd.c	\
			ft_putstr_fd.c	\
			ft_putendl_fd.c	\
			ft_putnbr_fd.c	\
			ft_calloc.c		\
			ft_strdup.c		\
			ft_substr.c		\
			ft_strjoin.c	\
			ft_strtrim.c	\
			ft_itoa.c		\
			ft_strmapi.c	\
			ft_striteri.c	\
			ft_split.c		\

HEAD_FILE = libft.h

OBJS	=	$(SRCS:.c=.o)
CC		=	cc
CFLAGS	=	-Wall -Wextra -Werror
RM		=	rm -f

all : $(NAME)

$(NAME)	: $(OBJS)
		ar rcs $(NAME) $(OBJS)

%.o: %.c $(HEAD_FILE)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS) $(BONUS_OBJS)

fclean: clean
	$(RM) $(NAME)

re:		fclean all

.PHONY: all clean fclean re bonus
